### ISSUE TITLE
Wiki markup within results

### ISSUE THREAD

**Issue by davidxn** [digitalduke/SQLquery#12]
Spectacular plugin - worked great out of the box!

Is it possible to allow wiki markup to be parsed within the results from the database? I'm particularly interested in links - I attempted ```SELECT CONCAT('[[games:', GaName, ']]')```, but that literally put the text [[games:ThisIsAGameName]] into the table.

Update: Links work if you use an < a > tag instead of the markup!

**Comment by digitalduke** [comment]
Hello @davidxn,

I think that is possible. I'll try to make this soon.

**Comment by bgenere** [comment]
You could achieve this by using HTML tag directly in the result set.
As an example this is a link with parameters from the request : 

` CONCAT("<b><a href='https://mydomain.fr/adherents/card.php?rowid=",adherent.rowid,"' target='_tab' >",adherent.rowid,"</a></b>") as 'Id',`
