### ISSUE TITLE
Get logged in user id for query

### ISSUE THREAD

**Issue by cbf305** [digitalduke/sqlquery#2]
Thanks for this extension it works very well.  I am trying to replace our old, custom built intranet with DokuWiki, and this extenstion lets me recreate all our database reports except for one.  The last one that I need requires the logged in user's ID as part of the query because it returns their demographic information so they can see what we have on file and provide updates.  I have tried the extension Variable plugin (https://www.dokuwiki.org/plugin:var) but the access variables it provide are treated as text inside the <sql> tags.  Which is kind of what I expected for security reasons, but is there any way internally to the plugin that one can grab the user ID by passing a specifc placeholder in the query that gets swapped out prior to execution?

Thanks!

**Comment by cbf305** [comment]
I was able to get it working by modifying the plugin (syntax.php) to look for the special place holder of `@uid@`.

After line 86 `$querystring = $data['sqlquery'];` I added the following line `$querystring = str_replace('@uid@', $_SERVER['REMOTE_USER'], $querystring);`

Basically if it sees the place holder it will swap it out with the currently logged in user id, otherwise it will leave the query untouched and then finish processing the query.

**Comment by digitalduke** [comment]
:+1:
