### ISSUE TITLE
No result(s) returned

### ISSUE THREAD

**Issue by MvErven** [digitalduke/sqlquery#4]
**Describe the bug**
Hello George. I have an issue I don't get any results (anymore) with the latest version of dukuwiki "Greebo" And MySQL 7.1 

**To Reproduce**
1. New page created
2. Added header
3. Added line: < sql> select * from customer; < / sql>
4. I See NO error messages or result

**Expected behavior**
I would expect a table with customers
Secondly I would have this table in the < datatables> tag from Bootswrapper 3

**Screenshots**
Nothing in screen, so no screenshot
 
**Desktop (please complete the following information):**
Windows 10
 - Browser Chrome 68 
 - IE 11 
 - FF 61

**Additional context**
I remembered this one from two years ago with "Elenor of Tsort" And working.
Perhaps an error is given, but not shown. I don't know. The database parameters are set and correct.
Thanks.

**Comment by MvErven** [comment]
Any update?

**Comment by digitalduke** [comment]
Hello Michiel,

is this issue still actual? Sorry, for my late answer.

**Comment by MvErven** [comment]
Hello, 
Thanks for the reply.
I've managed to get this to work again. But since I've enabled and disabled so many plugins. Updated them,  It may have been another plugin which resulted in this behavior.

Trail and error I guess. Have forgotten to close this.
Thank you for getting back.

Michiel.

**Comment by digitalduke** [comment]
:+1: 
Okay, sounds good. Feel free to open issues in the future.
